Deprecation Notice !
appium/appium-dot-exe pull request #176
Opened 2017-04-05 04:08 UTC by rkavalap

Deprecating appium-dot-exe. We need to move this to appium-boneyard.

2017-04-05 06:13 UTC, Astro03 requested changes
same to the comments in the appium-dot-app repo. 

I would like the README to still have the same stuff, but you can put the deprecation above the rest of it.. 

I only ask this because if people want to use the old repo, they can then see the readme that was associated with it

2017-04-06 06:31 UTC, rkavalap commented
@Astro03 Fixed here as well.

2017-04-10 20:34 UTC, Astro03 approved these changes

2017-04-10 20:35 UTC, Astro03 commented
LGTM

2017-04-10 20:35 UTC, merged